### ISSUE TITLE
Update Contributor Landing Page Copy - H1

### ISSUE THREAD

**Issue by PixelantDesign** [gitcoinco/Marketing#1]
Update Copy per Dean's recommendation

**Comment by deanramadan** [comment]
Please change the H1 to "Get Paid for Solving {Language} Issues". 

Also can we make the font smaller on the H1 and H2 and move everything up so that the four boxes in the 2nd section appear above the fold?

**Comment by thelostone-mc** [comment]
Oh I should start attending marketing calls to close these out faster :P
Anyways this should be the fix

![x](https://user-images.githubusercontent.com/5358146/44902210-f6749c80-ad26-11e8-9495-d6d334c55790.gif)

**Comment by thelostone-mc** [comment]
@PixelantDesign could you close this out?

**Comment by deanramadan** [comment]
wait, sorry, @thelostone-mc i'm still seeing the old copy on gitcoin.co/contributor. can we change that one to say "Get Paid for Solving Open Source Issues" and then the H2 "Gitcoin bounties pay when you submit a pull request."

**Comment by thelostone-mc** [comment]
@deanramadan taken care in #2238
