### ISSUE TITLE
Update Header on Mobile to be smaller

### ISSUE THREAD

**Issue by PixelantDesign** [gitcoinco/Marketing#2]
On the landing page the H1 is too large to read on mobile devices, make smaller.

**Comment by deanramadan** [comment]
![image 2](https://user-images.githubusercontent.com/42451046/44882727-79cfb880-ac69-11e8-9086-19e51835b58d.png)

We'd like to decrease font size on mobile for H1 and H2 so that both buttons appear above the fold

**Comment by thelostone-mc** [comment]
Aye aye @deanramadan 

![x](https://user-images.githubusercontent.com/5358146/44902538-e8734b80-ad27-11e8-8c44-ce186fa7199a.gif)

**Comment by PixelantDesign** [comment]
looks good!

**Comment by deanramadan** [comment]
Looks good to me, too! Thanks!

**Comment by thelostone-mc** [comment]
@PixelantDesign could you close this out ? ^_^
